### ISSUE TITLE
Automatically check "Do not delete devices"

### ISSUE THREAD

**Issue by Greenckson** [ioBroker/ioBroker.hm-rpc#100]
Automatically check "Do not delete devices" when creating a hmip instance. Otherwise e.g. settings like SQL logging will not be saved.

**Comment by foxriver76** [comment]
We only delete devices which are not synced anymore by CCU and therefore not appear in ``newDevices`` event. I am not 100 % sure when this happens, but I would expect it only to happen when a device is not known anymore by CCU. Thus, I think it's a comfortable option to have devices which I have removed from CCU being automatically deleted.

@Greenckson also I dont get why it only affects a HmIP instance and not any other instance?

**Comment by Apollon77** [comment]
> @Greenckson also I dont get why it only affects a HmIP instance and not any other instance?

because it is a bug in HMIP RPC Server ... they sometimes send all devices as "deleted" and ímmediately "readded" but this means that the hm-rpc instance removes all objects and recreate them (by looseing e.g. custom settings. That whay we added this option.

And yes for HMIO it makes sense to set this by default in admin when choosing hmip

**Comment by foxriver76** [comment]
Thanks for the explanation. Then it's no problem to autocheck it. :-)
