### ISSUE TITLE
HMIP-PSM imported with wrong properties

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/ioBroker.hm-rpc#151]
I've a HMIP-PSM, it looks in CCU like this:

<img width="1118" alt="bildschirmfoto 2019-02-07 um 00 28 09" src="https://user-images.githubusercontent.com/364896/52380734-42163980-2a6f-11e9-8362-4f5e358b2bb2.png">
 
in ioBroker it looks like this:

<img width="1293" alt="bildschirmfoto 2019-02-07 um 00 29 30" src="https://user-images.githubusercontent.com/364896/52380788-725dd800-2a6f-11e9-95ca-6edfb9bf72d2.png">

it seems to have completely wrong states defined.

**Comment by jogibear9988** [comment]
Ah, okay,
in channel 3 I could switch it.

But why for example do I have a "0" with a actual_temperature field?

**Comment by Hypnos3** [comment]
The channel 0 is the maintenance channel of a device. Every device hat this channel.

This channel is normally in the WebUI well hidden (but there you can also access them in programs and scripts).

In IOBroker (and other additional software) this channel is visible, because there are lot of useful datapoints (unreach, error states, ...).

In the device documentation of the HMIP-PSM is also stated the ACTUAL_TEMPERATURE datapoint.

**Comment by foxriver76** [comment]
Thanks for clarification @Hypnos3 
@jogibear9988 also your hm-rega instance seems to be older than stable or not correctly configured.

**Comment by foxriver76** [comment]
btw: @Hypnos3 where do you get these information from? May be helpful in the future, if these information are open source.

**Comment by Hypnos3** [comment]
These information are available at [eq-3](https://www.eq-3.de/), the manufacturer of the Homematic products.

In the [Device Documentation for the HmIp products](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf) you can find starting from chapter 67 the documentation of the HMIP-PSM device. (similar documentation can be found for the Homematic RF and Homematic Wired products at [www.eq-3.de](https://www.eq-3.de/service/downloads.html))

As I can see there, the ACTUAL_TEMPERATURE in the channel 0 MAINTENANCE is available since Version 3 of the device.

In that documentation are only the technical data documented and unfortunately not what their purpose. If you need the purpose you have to find out this yourself or search the Internet. A good point of star here is the german homematic forum https://homematic-forum.de/

**Comment by foxriver76** [comment]
Very helpful document. Thank you very much :-)
