### ISSUE TITLE
Error on getParamsetDescription: Error: XML-RPC fault: Unknown paramset

### ISSUE THREAD

**Issue by PowerMung** [ioBroker/ioBroker.hm-rpc#256]
**Describe the bug**
Nach initialem Starten des Adapters bekomme ich folgende Meldung im Log:
Error on getParamsetDescription: Error: XML-RPC fault: Unknown paramset
Zunächst scheint das Auslesen zu funktionieren, der Prozess stoppt aber immer an der gleichen Stelle mit oben genannter Meldung. Es fehlen dann auch entsprechende Einträge unter Objekte.
Mehrfaches Neuinstallieren des Rega-Adapters als auch des RPC-Adapters führen auch nicht zum Erfolg.
Ich habe dann nach und nach ältere Versionen vom hm-rpc Adapter installiert.
Version 1.14.10 liefert das gleiche Problem.
Version 1.14.5 funktioniert!!! Die Initialisierung läuft komplett ohne Fehler durch und alle Objekte werden richtig angelegt!
Die Version 1.14.6 habe ich nicht getestet.

**To Reproduce**
-
**Expected behavior**
-
**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/67764917/86415715-26e14500-bcc8-11ea-8bff-d21d2c1326c1.png)

**Versions:**
 - hm-rpc version: 1.14.11
 - hm-rega version: 2.6.14
 - JS-Controller version: 3.1.6
 - Node version: 12.18.1
 - Operating system: linux
 - CCU model: raspberrymatic
 - CCU firmware: 3.51.6.20200621

**Additional context**
-

**Comment by foxriver76** [comment]
Meta data are no longer provided i cached form by the adapter. Thus, every meta object will be requested on the CCU. However, there is a problem, if CCU returns an error, because this currently stops the execution, while it shouldn't. But the problem that an error is returned lies on CCU side, idk what "NEQ0103340", then we should see if channel 3 should exist. I will push an adapted version, which won't stop execution in such cases.
