### ISSUE TITLE
Property "Verbindungs-Test Intervall(s)" is ignored

### ISSUE THREAD

**Issue by dklinger** [ioBroker/ioBroker.hm-rpc#313]
Hi,

**Describe the bug**
According to the log and my DNS-Server, the Ping occurs afters 90 seconds. The interval set in "Verbindungs-Test Intervall(s)" property in the Additional Settings is divided by 2.

**Steps to reproduce the behavior**
1. Go to adapter settings
2. Go to tab "Zusätzliche Einstellungen"
3. Check property "Verbindungs-Test Intervall(s)" 
4. Save
5. Set Logging of the adapter to debug
6. Have a look at the logs - PING occurs after half the time set in the property

**Expected behavior**
Ping is sent to CCU after the time defined in settings

**Versions:**
hm-rpc version: v1.14.35
hm-rega version: v3.0.16
JS-Controller version: v3.2.16
Node version: v12.20.2
Operating system: docker (buanet:latest-v5 - 2021-02-20)
CCU model: CCU2
CCU firmware: 2.55.10

Problematic line:
https://github.com/ioBroker/ioBroker.hm-rpc/blob/b7c9f9f1fb8afa6310f94ed0b223acf21388a8e2/main.js#L1682

So, is this by intention?

**Comment by dklinger** [comment]
@GermanBluefox changed this 6 years ago, so there's probably some magic behind it :)

https://github.com/ioBroker/ioBroker.hm-rpc/commit/f03112de1872d51e20a0d6d69c1396d3283584b8

**Comment by foxriver76** [comment]
It's not implemented by myself, but it looks pretty intended. It `checkInitInterval` is divided by 2 and ping is requested. I guess the problem lies somewhere, that we send ping and then we need to wait if the ping is answered. By sending two pings in the `checkInitInterval` at least the first should be answered when we check for the timeout case https://github.com/ioBroker/ioBroker.hm-rpc/blob/b7c9f9f1fb8afa6310f94ed0b223acf21388a8e2/main.js#L1777

And I guess it's by purpose not called `pingInterval`.

Question is, are there any issues in your setup because of this behavior?

**Comment by dklinger** [comment]
Yes, from the timeout perspective it makes sense. 

I don't have any issues but was just wondering as I have 5 instances of hm-rpc and my PiHole-DNS is getting close to 5000 queries from ioBroker a day, asking for the HOST-A entry of the CCU. So I started digging around why the iobroker is sending so many requests.
The "solution" for me is easy: Changing the CCC-DNS-Name in the adapters settings to the IP of the CCU, but I also wanted to understand why there are so many requests.

Thanks for the clarification. I'll close the issue.
